### ISSUE TITLE
What is the difference between LoadSkeletalAnimation and LoadNodeSkeleletalAnimation?

### ISSUE THREAD

**Issue by sunrui19941128** [rdeioris/glTFRuntime-docs#16]
I would like to know the difference between these two methods. The glb I loaded in UE cannot be played. Can you provide a screenshot of the blueprint,
I found that this glb has been parsed as nodeAnimation, but it cannot be played no matter what
[Soldier.zip](https://github.com/user-attachments/files/16061139/Soldier.zip)

**Comment by rdeioris** [comment]
Hi, Unreal expects animations to be backed up by a skeleton, while glTF allows to animate the transform of any node. For this reason, in addition to standard Skeletal Animations (the ones you extract with LoadSkeletalAnimation) there is a pure-curves extractor that just extracts an array of transforms you can apply as you prefer (there is a pretty naive example in the glTFRuntimeAssetActor class using the Tick).
Your asset has nothing particular, it is a plain skeletal animations (well there are 4 of them). You can just use the provided glTFRuntimeAssetActor and you will get the idle animation (it is the first one). Otherwise (once you have the skeletalmesh) you can load one of the 4 with LoadSkeletalAnimation()
