### ISSUE TITLE
Complex Collision Crashing

### ISSUE THREAD

**Issue by keiddzz** [rdeioris/glTFRuntime-docs#18]
I'm trying to put collision on my model, my model has many nodes, and I don't know how to put the model in the outer, since I've tried many things and it always crashes.

Blueprint: https://blueprintue.com/blueprint/dz_072p0/

**Comment by rdeioris** [comment]
Hi, this is from the docs:

"""You can even set a complex collision by changing the collision complexity field, in such a case ensure to enable the AllowCPUAccess flag and an Outer set (generally the StaticMeshComponent will be enough, the Runtime Asset Actor already does it automatically), otherwise the physics engine will not be able to generate the related shape."""

In your example the Outer is not set (check the glTFRuntimeAssetActor to see how it works under the hood). What is a bit weird is the crash, ccan you report the traceback?

**Comment by keiddzz** [comment]
Oh sorry, I forgot to connect it in the example, but yes, if I connect it it crashes, I think I'm doing it wrong, but I don't know how to connect it, I looked at all the docs and nothing. 

Blueprint: https://blueprintue.com/blueprint/e7sggkst/

**Comment by rdeioris** [comment]
Please provide the traceback of the crash otherwise i have no way to understand what is going on.

**Comment by keiddzz** [comment]
I've solved it! To build the collisions it has to be in runtime, because if you do it before, it crashes (since I have a button to load the map), also I had to enable: "Build Complex Collisions" in the configuration. Anyway, thank you very much for trying to help me!
